package Pokemon;

public enum Tipo {

    ACERO, AGUA, BICHO,
    DRAGON, ELECTRICO, FANTASMA,
    FUEGO, HADA, HIELO,
    LUCHA, NORMAL, PLANTA,
    PSIQUICO, ROCA, SINIESTRO,
    TIERRA, VENENO, VOLADOR,
    NORMALVOLADOR
}
